### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by lubegasimon**
I thought that the js files were added to the .gitignore file, but suprisingly, they still appear in my commits.

### CODE REVIEW

**Comment by epicallan** [comment]
you should use `git rm --cache <filename>` to remove them from git history and then push again.

**Comment by lubegasimon** [comment]
sure, though this sounds like some other option, could anything have been wrong with my .gitignore file??

**Comment by epicallan** [comment]
nop, its just the way git work. If you already committed files into git history you need to remove them for them to be out of your git history even with them being in .gitignore

**Comment by epicallan** [comment]
you can also ignore all JavaScript files by adding `*.js` to .gitignore instead of adding multiple files

**Comment by lubegasimon** [comment]
i did so in the first place, and things mis-behaved 
https://github.com/lubegasimon/CL-shell-in-ts/pull/3/commits/a2cee2faf10a170513aec605a4d97979d8046be1

**Comment by epicallan** [comment]
could you merge in this PR and then I will write you some new issues to work on.

**Pull request merged**
